
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Video, Play } from 'lucide-react';
import "./globals.css";

import {
  Box,
  Container,
  Typography,
  Button,
  IconButton,
  Divider,
  OutlinedInput

} from "@mui/material"
import { GenraType } from "./type/global";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// This is genra list 
async function fetchGenralist(): Promise<GenraType> {

  const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
    headers: {
      "Authorization": `Bearer ${process.env.TMDB_KEY}`,
    },
  });

  const data = await res.json()

  return data.genres;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const genres = await fetchGenralist();
  return (
    <html lang="en">
      <body   className={`${geistSans.variable} ${geistMono.variable}`}>
         
            
        <Container maxWidth="xl" sx={{}} >
          <Box
            sx={{

              display: "flex",
              alignItems: 'center',
              justifyContent: 'space-between',
              // borderBottom: '1px solid rgba(0,0,0,0.2)',
              p: 2,
              width : "90vw"
            }}
          > 
           <Box sx={{display : "flex"}}>

            <Typography sx={{ fontSize: 28, fontWeight: 'bold', flexGrow: 1 ,}}>
              Next Movie
            </Typography>

            <IconButton type="submit">
              <Video size={28} />
            </IconButton>
           </Box>

           <Box>
                  <form action="" style={{display : "flex"}} >
                    <OutlinedInput  placeholder="Search ...."  sx={{width : "300px" , height : "38px" }} />
                    <Button sx={{marginLeft : 3}} color="success" variant="contained">Serch</Button>
                  </form>
           </Box>
          </Box>
          <Divider sx={{ width: '100vw' }} />

        </Container>
          
        <Container maxWidth="xl" sx={{ display: "flex", gap: '12px' }}>
          <Box sx={{
            width: "200px", paddingRight: 4,
            borderRight: '1px solid rgba(0,0,0,0.2)',

          }}>
            <Box sx={{ width: "200px", display: "flex ", gap: 1, mt: 2, flexDirection: 'column' }}>


              <Button  href="/" variant="outlined" startIcon={<Play size={18} />}
                sx={{ display: 'flex', justifyContent: 'flex-start' }}   > 
                
                  All
                 
                 </Button>
              { genres.map( (genre : GenraType)  => (
                <Button  
                href={`/genre/${genre.name}/${genre.id}`}
                   
                  key={genre.id}
                  variant="outlined"
                  startIcon={<Play size={18} />}
                  sx={{ display: 'flex', justifyContent: 'flex-start' }}
                > 
                  {genre.name} 
                
                </Button>
              ))}


            </Box>
          </Box>
          <Box sx={{ p: 4 }}>
            {children}
          </Box>

        </Container>

      </body>
    </html>
  );
}
